### ISSUE TITLE
Theory of the code

### ISSUE THREAD

**Issue by robopassio** [meco-group/rtPGM#1]
I tried to understand the theory of proposing the following code, but I can not:
`        # relation between reference and steady-state state & input

        Tinv = np.vstack((np.hstack((self.A - np.eye(self.nx), self.B)),
                          np.hstack((self.C, np.zeros((self.C.shape[0], self.nu))))))

        T = np.linalg.solve(Tinv, np.eye(Tinv.shape[0])).dot(
            np.vstack((np.zeros((self.nx, 1)), np.ones((self.ny, 1)))))`

Could you please help me to provide the theory/concept of how you can establish this one?
Thank you so much!

**Comment by robopassio** [comment]
Dear Dr. Ruben Van Parys,
I am still looking forward to hearing from you. I could not send you by email. Could you please help to advise or give me some related links?

**Comment by rubenvanparys** [comment]
Hi! I'll try to answer you to upcoming days! Currently, I'm quite busy...

**Comment by rubenvanparys** [comment]
With steady-state state (x_ss), input (u_ss) and output (y_ss), I mean the values for which the following steady-state equation hold:
x_ss = A * x_ss + B * u_ss
y_ss = C * x_ss

`Tinv` expresses the following relationship:
[0; y_ss] = Tinv * [x_ss; u_ss]
and can be derived using the above mentioned steady-state equation.

`T` expresses the relation between [x_ss; u_ss] and y_ss:
[x_ss; u_ss] = T * y_ss
and is computed by inverting `Tinv` and multiplying by [0; y_ss]

Further, `Tx` and `Tu` are slices of T and express the relation between x_ss, u_ss respectively and y_ss:
x_ss = Tx * y_ss
u_ss = Tu * y_ss

I hope this answers your questions?

**Comment by robopassio** [comment]
Dear Dr. Ruben Van Parys,
Thank you so much for your reply! I got your point.
May I have your email to have further discussion/cooperation in the future?
Since I tried to contact you by ruben.vanparys@kuleuven.be, however, the mail system notified that it could not be sent (I tried both on Gmail and Yahoo mail!)
Hope to hear from you!

**Comment by rubenvanparys** [comment]
Yes of course! I am sure you can find my e-mail or some way to send me a personal message somewhere on the net ;)
